### ISSUE TITLE
Supervisor when offline

### ISSUE THREAD

**Issue by abkfenris** [abkfenris/gage-beaglebone#21]
It appears that the supervisor doesn't respond when the device is offline

```bash
15.04.17 08:49:36 (-0400) Traceback (most recent call last):
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/co
nnection.py", line 141, in _new_conn
15.04.17 08:49:36 (-0400)     (self.host, self.port), self.timeout, **extra_kw)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/ut
il/connection.py", line 83, in create_connection
15.04.17 08:49:36 (-0400)     raise err
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/ut
il/connection.py", line 73, in create_connection
15.04.17 08:49:36 (-0400)     sock.connect(sa)
15.04.17 08:49:36 (-0400) ConnectionRefusedError: [Errno 111] Connection refused
15.04.17 08:49:36 (-0400)
15.04.17 08:49:36 (-0400) During handling of the above exception, another exception occurred:
15.04.17 08:49:36 (-0400)
15.04.17 08:49:36 (-0400) Traceback (most recent call last):
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/co
nnectionpool.py", line 600, in urlopen
15.04.17 08:49:36 (-0400)     chunked=chunked)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/co
nnectionpool.py", line 356, in _make_request
15.04.17 08:49:36 (-0400)     conn.request(method, url, **httplib_request_kw)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
15.04.17 08:49:36 (-0400)     self._send_request(method, url, body, headers, encode_chunked)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_reque
st
15.04.17 08:49:36 (-0400)     self.endheaders(body, encode_chunked=encode_chunked)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
15.04.17 08:49:36 (-0400)     self._send_output(message_body, encode_chunked=encode_chunked)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_outpu
t
15.04.17 08:49:36 (-0400)     self.send(msg)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/http/client.py", line 964, in send
15.04.17 08:49:36 (-0400)     self.connect()
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/co
nnection.py", line 166, in connect
15.04.17 08:49:36 (-0400)     conn = self._new_conn()
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/co
nnection.py", line 150, in _new_conn
15.04.17 08:49:36 (-0400)     self, "Failed to establish a new connection: %s" % e)
15.04.17 08:49:36 (-0400) requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages
.urllib3.connection.HTTPConnection object at 0xb5eac6f0>: Failed to establish a new connection: [Errn
o 111] Connection refused
15.04.17 08:49:36 (-0400)
15.04.17 08:49:36 (-0400) During handling of the above exception, another exception occurred:
15.04.17 08:49:36 (-0400)
15.04.17 08:49:36 (-0400) Traceback (most recent call last):
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line
423, in send
15.04.17 08:49:36 (-0400)     timeout=timeout
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/co
nnectionpool.py", line 649, in urlopen
15.04.17 08:49:36 (-0400)     _stacktrace=sys.exc_info()[2])
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/ut
il/retry.py", line 376, in increment
15.04.17 08:49:36 (-0400)     raise MaxRetryError(_pool, url, error or ResponseError(cause))
15.04.17 08:49:36 (-0400) requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host
='127.0.0.1', port=48484): Max retries exceeded with url: /v1/device?apikey=d4cbb0735b7100206bcc8e174
368724232a14cddd95c55ca2f5dde72c8e47550 (Caused by NewConnectionError('<requests.packages.urllib3.con
nection.HTTPConnection object at 0xb5eac6f0>: Failed to establish a new connection: [Errno 111] Conne
ction refused',))
15.04.17 08:49:36 (-0400)
15.04.17 08:49:36 (-0400) During handling of the above exception, another exception occurred:
15.04.17 08:49:36 (-0400)
15.04.17 08:49:36 (-0400) Traceback (most recent call last):
15.04.17 08:49:36 (-0400)   File "simple.py", line 205, in <module>
15.04.17 08:49:36 (-0400)     if pcape.update_in_progress():
15.04.17 08:49:36 (-0400)   File "/gage/pcape.py", line 196, in update_in_progress
15.04.17 08:49:36 (-0400)     headers={'Content-Type': 'application/json'})
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 70, i
n get
15.04.17 08:49:36 (-0400)     return request('get', url, params=params, **kwargs)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 56, i
n request
15.04.17 08:49:36 (-0400)     return session.request(method=method, url=url, **kwargs)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line
488, in request
15.04.17 08:49:36 (-0400)     resp = self.send(prep, **send_kwargs)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line
609, in send
15.04.17 08:49:36 (-0400)     r = adapter.send(request, **kwargs)
15.04.17 08:49:36 (-0400)   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line
487, in send
15.04.17 08:49:36 (-0400)     raise ConnectionError(e, request=request)
15.04.17 08:49:36 (-0400) requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', p
ort=48484): Max retries exceeded with url: /v1/device?apikey=d4cbb0735b7100206bcc8e174368724232a14cdd
d95c55ca2f5dde72c8e47550 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPCon
nection object at 0xb5eac6f0>: Failed to establish a new connection: [Errno 111] Connection refused',
))
15.04.17 08:49:37 (-0400) /usr/bin/entry.sh: line 93: fg: job has terminated
```
The container then restarts in a loop while waiting for it.

**Comment by abkfenris** [comment]
Need to check if it can still shutdown.

**Comment by abkfenris** [comment]
^ Nope

**Comment by abkfenris** [comment]
Can power off with 
```bash
dbus-send --system --print-reply --dest=org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.PowerOff
```

after `apt-get install dbus`

May be possible from python too

**Comment by abkfenris** [comment]
```python
import dbus
bus = dbus.SystemBus()
bus_object = bus.get_object('org.freedesktop.systemd1', '/org/freedesktop/systemd1')
bus_object.PowerOff(dbus_interface='org.freedesktop.systemd1.Manager')
```

**Comment by abkfenris** [comment]
Turns out there is an issue with the supervisor resin-io/resin-supervisor#420 resin-io/resin-supervisor#421 . The latest version of the agent 4.1.2 has the fix, but currently running on 4.1.1.
